### ISSUE TITLE
Whose?

### ISSUE THREAD

**Issue by tenasatupitsyn** [akaryos/api#1]
Creation does not conform to the defined schema
https://github.com/akaryos/api/blob/829a4eaeedd4a151af2cd01e46fbbeb8f567a469/core/database/schemas/InviteSchema.js#L4
https://github.com/akaryos/api/blob/829a4eaeedd4a151af2cd01e46fbbeb8f567a469/core/routes/auth.routes.js#L36
This project is undergoing some test?

**Comment by samueldurantes** [comment]
The typeof `username` is an String.

**Comment by tenasatupitsyn** [comment]
whose not **whoose**
I see you really understand what you're doing, congrats!

**Comment by samueldurantes** [comment]
Now got it, thanks for letting me know.

**Comment by tenasatupitsyn** [comment]
Correct the label and mention the correction in that issue

**Comment by samueldurantes** [comment]
https://github.com/akaryos/api/commit/5100ecd2106e09f23427aaccad14d4fdf0e2c6fe

**Comment by samueldurantes** [comment]
fixed https://github.com/akaryos/api/commit/5100ecd2106e09f23427aaccad14d4fdf0e2c6fe
